version: '3.8'
services:
  backend-container:
    build: . # Tells Docker to look for a 'Dockerfile' in the current directory to build the image
    ports:
      - "5000:5000"
    networks: # Connects this specific container to a network
      - saas-network
    volumes:
      - .:/app               # Mounts your local folder into the container
      - /app/node_modules    # Tells Docker NOT to overwrite the container's node_modules
    environment:
      - DATABASE_URL=postgresql://yuvraj:password@db:5432/nexus-api-db
  
  db:
    image: postgres:15
    environment: # Configures the database credentials via environment variables
      POSTGRES_USER: yuvraj # Sets the master username for the database
      POSTGRES_PASSWORD: password # Sets the password for the database user
      POSTGRES_DB: nexus-api-db
    ports:
      - "5432:5432"
    networks:
      - saas-network

networks: # Defines the networks used in this compose file
  saas-network: # The name of the network we are defining
    external: true # Tells Docker NOT to create this network, but to look for an existing one we created manually